// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gsmservice-pl/messaging-sdk-go/v3/models/components"
)

type AddSenderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully (sender created)
	Sender  *components.Sender
	Headers map[string][]string
}

func (a *AddSenderResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddSenderResponse) GetSender() *components.Sender {
	if a == nil {
		return nil
	}
	return a.Sender
}

func (a *AddSenderResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
