// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gsmservice-pl/messaging-sdk-go/v3/models/components"
)

type CancelMessagesRequest struct {
	// Array of Message IDs assigned by the system. The system will accept a maximum of 50 identifiers in one call.
	Ids []int64 `pathParam:"style=simple,explode=true,name=ids"`
}

func (c *CancelMessagesRequest) GetIds() []int64 {
	if c == nil {
		return []int64{}
	}
	return c.Ids
}

type CancelMessagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Please check the status of messages cancellation in `Status` property of each `CancelledMessage` object.
	CancelledMessages []components.CancelledMessage
	Headers           map[string][]string
}

func (c *CancelMessagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelMessagesResponse) GetCancelledMessages() []components.CancelledMessage {
	if c == nil {
		return nil
	}
	return c.CancelledMessages
}

func (c *CancelMessagesResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
