// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gsmservice-pl/messaging-sdk-go/v3/models/components"
)

type GetAccountDetailsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully
	AccountResponse *components.AccountResponse
}

func (g *GetAccountDetailsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAccountDetailsResponse) GetAccountResponse() *components.AccountResponse {
	if g == nil {
		return nil
	}
	return g.AccountResponse
}
