// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gsmservice-pl/messaging-sdk-go/models/components"
)

type GetAccountDetailsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully
	AccountResponse *components.AccountResponse
}

func (o *GetAccountDetailsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAccountDetailsResponse) GetAccountResponse() *components.AccountResponse {
	if o == nil {
		return nil
	}
	return o.AccountResponse
}
