// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gsmservice-pl/messaging-sdk-go/v3/models/components"
)

type GetMessagesRequest struct {
	// Array of Message IDs assigned by the system. The system will accept a maximum of 50 identifiers in one call.
	Ids []int64 `pathParam:"style=simple,explode=true,name=ids"`
}

func (g *GetMessagesRequest) GetIds() []int64 {
	if g == nil {
		return []int64{}
	}
	return g.Ids
}

type GetMessagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Please check messages details in each `Message` object.
	Messages []components.Message
	Headers  map[string][]string
}

func (g *GetMessagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMessagesResponse) GetMessages() []components.Message {
	if g == nil {
		return nil
	}
	return g.Messages
}

func (g *GetMessagesResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
