// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/gsmservice-pl/messaging-sdk-go/internal/utils"
	"github.com/gsmservice-pl/messaging-sdk-go/models/components"
)

type GetSmsPriceRequestBodyType string

const (
	GetSmsPriceRequestBodyTypeSms        GetSmsPriceRequestBodyType = "Sms"
	GetSmsPriceRequestBodyTypeArrayOfSms GetSmsPriceRequestBodyType = "arrayOfSms"
)

// GetSmsPriceRequestBody - To check the price of a single SMS or messages with the same content to multiple recipients, pass in the Request Body a single `Sms` object with the properties of this message. To check the price of multiple messages with different content at the same time, pass in the Request Body an `array` of `Sms` objects with the properties of each message.
type GetSmsPriceRequestBody struct {
	Sms        *components.Sms
	ArrayOfSms []components.Sms

	Type GetSmsPriceRequestBodyType
}

func CreateGetSmsPriceRequestBodySms(sms components.Sms) GetSmsPriceRequestBody {
	typ := GetSmsPriceRequestBodyTypeSms

	return GetSmsPriceRequestBody{
		Sms:  &sms,
		Type: typ,
	}
}

func CreateGetSmsPriceRequestBodyArrayOfSms(arrayOfSms []components.Sms) GetSmsPriceRequestBody {
	typ := GetSmsPriceRequestBodyTypeArrayOfSms

	return GetSmsPriceRequestBody{
		ArrayOfSms: arrayOfSms,
		Type:       typ,
	}
}

func (u *GetSmsPriceRequestBody) UnmarshalJSON(data []byte) error {

	var sms components.Sms = components.Sms{}
	if err := utils.UnmarshalJSON(data, &sms, "", true, true); err == nil {
		u.Sms = &sms
		u.Type = GetSmsPriceRequestBodyTypeSms
		return nil
	}

	var arrayOfSms []components.Sms = []components.Sms{}
	if err := utils.UnmarshalJSON(data, &arrayOfSms, "", true, true); err == nil {
		u.ArrayOfSms = arrayOfSms
		u.Type = GetSmsPriceRequestBodyTypeArrayOfSms
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetSmsPriceRequestBody", string(data))
}

func (u GetSmsPriceRequestBody) MarshalJSON() ([]byte, error) {
	if u.Sms != nil {
		return utils.MarshalJSON(u.Sms, "", true)
	}

	if u.ArrayOfSms != nil {
		return utils.MarshalJSON(u.ArrayOfSms, "", true)
	}

	return nil, errors.New("could not marshal union type GetSmsPriceRequestBody: all fields are null")
}

type GetSmsPriceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Please check the price and the details of particular messages in response body
	Prices  []components.Price
	Headers map[string][]string
}

func (o *GetSmsPriceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSmsPriceResponse) GetPrices() []components.Price {
	if o == nil {
		return nil
	}
	return o.Prices
}

func (o *GetSmsPriceResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
