// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gsmservice-pl/messaging-sdk-go/v3/models/components"
)

type GetSubaccountDetailsRequest struct {
	// Login of the subaccount (user) to get the data for
	UserLogin string `pathParam:"style=simple,explode=true,name=user_login"`
}

func (g *GetSubaccountDetailsRequest) GetUserLogin() string {
	if g == nil {
		return ""
	}
	return g.UserLogin
}

type GetSubaccountDetailsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully
	AccountResponse *components.AccountResponse
}

func (g *GetSubaccountDetailsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubaccountDetailsResponse) GetAccountResponse() *components.AccountResponse {
	if g == nil {
		return nil
	}
	return g.AccountResponse
}
