// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gsmservice-pl/messaging-sdk-go/v3/models/components"
)

type PingResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// API service is available
	PingResponse *components.PingResponse
}

func (o *PingResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PingResponse) GetPingResponse() *components.PingResponse {
	if o == nil {
		return nil
	}
	return o.PingResponse
}
