// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

// ErrorResponse - An object that complies with RFC 9457 containing information about a request error
type ErrorResponse struct {
	// A URI reference that identifies the problem type
	Type *string `json:"type,omitempty"`
	// The HTTP status code generated by the origin server for this occurrence of the problem
	Status *int64 `json:"status,omitempty"`
	// A short, human-readable summary of the problem type
	Title *string `json:"title,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`
	// An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry
	Code *string `json:"code,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem
	Instance *string `json:"instance,omitempty"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	if e.Detail == nil {
		return "unknown error"
	}

	return *e.Detail
}
