// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CancelledMessage - An object containing information about results of cancelling single message
type CancelledMessage struct {
	// Message ID
	ID *int64 `json:"id,omitempty"`
	// Status of cancellation (204 if cancelled successfully or error status code)
	Status *int64 `json:"status,omitempty"`
	// An object that complies with RFC 9457 containing information about a request error
	Error *ErrorResponse `json:"error,omitempty"`
}

func (c *CancelledMessage) GetID() *int64 {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CancelledMessage) GetStatus() *int64 {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CancelledMessage) GetError() *ErrorResponse {
	if c == nil {
		return nil
	}
	return c.Error
}
