// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorResponse - An object that complies with RFC 9457 containing information about a request error
type ErrorResponse struct {
	// A URI reference that identifies the problem type
	Type *string `json:"type,omitempty"`
	// The HTTP status code generated by the origin server for this occurrence of the problem
	Status *int64 `json:"status,omitempty"`
	// A short, human-readable summary of the problem type
	Title *string `json:"title,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`
	// An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry
	Code *string `json:"code,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem
	Instance *string `json:"instance,omitempty"`
}

func (o *ErrorResponse) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *ErrorResponse) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ErrorResponse) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *ErrorResponse) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *ErrorResponse) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ErrorResponse) GetInstance() *string {
	if o == nil {
		return nil
	}
	return o.Instance
}
