// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gsmservice-pl/messaging-sdk-go/v3/internal/utils"
	"time"
)

// IncomingMessage - An object with the properties of the received message
type IncomingMessage struct {
	// Unique identifier of incoming message
	ID *int64 `json:"id,omitempty"`
	// Login of the account (sub-account) on which the message was received
	Login *string `json:"login,omitempty"`
	// Recipient number (or service name)
	Recipient *string `json:"recipient,omitempty"`
	// Message sender number (or alphanumeric name)
	Sender *string `json:"sender,omitempty"`
	// Sender name (matched with phonebook)
	PhonebookSenderName *string `json:"phonebook_sender_name,omitempty"`
	// Date and time of message receipt in ISO 8601 format
	Date *time.Time `json:"date,omitempty"`
	// Received message content
	Message *string `json:"message,omitempty"`
	// Dedicated Mobile Originated service number (if the message was received on this number)
	DedicatedNumber *string `json:"dedicated_number,omitempty"`
	// Dedicated Mobile Originated service prefix (if the message was received on this number with such prefix)
	DedicatedPrefix *string `json:"dedicated_prefix,omitempty"`
}

func (i IncomingMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IncomingMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IncomingMessage) GetID() *int64 {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IncomingMessage) GetLogin() *string {
	if i == nil {
		return nil
	}
	return i.Login
}

func (i *IncomingMessage) GetRecipient() *string {
	if i == nil {
		return nil
	}
	return i.Recipient
}

func (i *IncomingMessage) GetSender() *string {
	if i == nil {
		return nil
	}
	return i.Sender
}

func (i *IncomingMessage) GetPhonebookSenderName() *string {
	if i == nil {
		return nil
	}
	return i.PhonebookSenderName
}

func (i *IncomingMessage) GetDate() *time.Time {
	if i == nil {
		return nil
	}
	return i.Date
}

func (i *IncomingMessage) GetMessage() *string {
	if i == nil {
		return nil
	}
	return i.Message
}

func (i *IncomingMessage) GetDedicatedNumber() *string {
	if i == nil {
		return nil
	}
	return i.DedicatedNumber
}

func (i *IncomingMessage) GetDedicatedPrefix() *string {
	if i == nil {
		return nil
	}
	return i.DedicatedPrefix
}
