// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MessageType - Message type (components.MessageTypeSmsPro -> SMS PRO, components.MessageTypeSmsEco -> SMS ECO, components.MessageTypeSmsTwoWay ->SMS 2WAY, components.MessageTypeMms -> MMS)
type MessageType int64

const (
	MessageTypeSmsPro    MessageType = 1
	MessageTypeSmsEco    MessageType = 3
	MessageTypeSmsTwoWay MessageType = 4
	MessageTypeMms       MessageType = 10
)

func (e MessageType) ToPointer() *MessageType {
	return &e
}
