// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PhoneNumberWithCid - An object defining the message recipient telephone number with the message's custom identifier assigned by the User
type PhoneNumberWithCid struct {
	// A telephone number in international format (with a plus sign and the country code at the beginning, e.g. +48 for Poland)
	Nr string `json:"nr"`
	// Custom message ID assigned by the User
	Cid *string `json:"cid,omitempty"`
}

func (o *PhoneNumberWithCid) GetNr() string {
	if o == nil {
		return ""
	}
	return o.Nr
}

func (o *PhoneNumberWithCid) GetCid() *string {
	if o == nil {
		return nil
	}
	return o.Cid
}
