// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PingResponse - 'Ping' response object
type PingResponse struct {
	// API service status: OK - API available, ERR - API unavailable
	Status *string `json:"status,omitempty"`
	// Current API Version
	Version *string `json:"version,omitempty"`
	// Was the connection established with the test system (SANDBOX)?
	Sandbox *bool `json:"sandbox,omitempty"`
}

func (p *PingResponse) GetStatus() *string {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PingResponse) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PingResponse) GetSandbox() *bool {
	if p == nil {
		return nil
	}
	return p.Sandbox
}
