// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Price - An object with the properties and price of a single message
type Price struct {
	// Information about a possible error
	Error *string `json:"error,omitempty"`
	// Custom message ID assigned by the User
	Cid *string `json:"cid,omitempty"`
	// Message type (components.MessageTypeSmsPro -> SMS PRO, components.MessageTypeSmsEco -> SMS ECO, components.MessageTypeSmsTwoWay ->SMS 2WAY, components.MessageTypeMms -> MMS)
	Type      *MessageType `json:"type,omitempty"`
	Recipient *string      `json:"recipient,omitempty"`
	// Message sender name
	Sender *string `json:"sender,omitempty"`
	// The count of parts that message consists of
	Parts *int64 `json:"parts,omitempty"`
	// Did the message contain special characters, e.g. Polish diacritics?
	Unicode *bool `json:"unicode,omitempty"`
	// Was the message sent with class 0 (FLASH)?
	Flash *bool `json:"flash,omitempty"`
	// The price of message (in PLN)
	Price *float32 `json:"price,omitempty"`
}

func (o *Price) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *Price) GetCid() *string {
	if o == nil {
		return nil
	}
	return o.Cid
}

func (o *Price) GetType() *MessageType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Price) GetRecipient() *string {
	if o == nil {
		return nil
	}
	return o.Recipient
}

func (o *Price) GetSender() *string {
	if o == nil {
		return nil
	}
	return o.Sender
}

func (o *Price) GetParts() *int64 {
	if o == nil {
		return nil
	}
	return o.Parts
}

func (o *Price) GetUnicode() *bool {
	if o == nil {
		return nil
	}
	return o.Unicode
}

func (o *Price) GetFlash() *bool {
	if o == nil {
		return nil
	}
	return o.Flash
}

func (o *Price) GetPrice() *float32 {
	if o == nil {
		return nil
	}
	return o.Price
}
