// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Sender - An object with the properties of the message sender
type Sender struct {
	// Message sender name
	Sender string `json:"sender"`
	// Sender name status
	Status string `json:"status"`
	// Is the sender default?
	IsDefault bool `json:"is_default"`
}

func (s *Sender) GetSender() string {
	if s == nil {
		return ""
	}
	return s.Sender
}

func (s *Sender) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *Sender) GetIsDefault() bool {
	if s == nil {
		return false
	}
	return s.IsDefault
}
