// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SenderInput - An object with the properties of the message sender
type SenderInput struct {
	// Message sender name
	Sender string `json:"sender"`
	// Description of the purpose of the sender name (required when adding new sender name)
	Description string `json:"description"`
}

func (o *SenderInput) GetSender() string {
	if o == nil {
		return ""
	}
	return o.Sender
}

func (o *SenderInput) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}
