// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Sender - An object with the properties of the message sender
type Sender struct {
	// Message sender name
	Sender string `json:"sender"`
	// Sender name status
	Status string `json:"status"`
	// Is the sender default?
	IsDefault bool `json:"is_default"`
}

func (o *Sender) GetSender() string {
	if o == nil {
		return ""
	}
	return o.Sender
}

func (o *Sender) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *Sender) GetIsDefault() bool {
	if o == nil {
		return false
	}
	return o.IsDefault
}
