// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SmsType - SMS type (components.SmsTypeSmsPro -> SMS PRO, components.SmsTypeSmsEco -> SMS ECO, components.SmsTypeSmsTwoWay -> SMS 2WAY)
type SmsType int64

const (
	SmsTypeSmsPro    SmsType = 1
	SmsTypeSmsEco    SmsType = 3
	SmsTypeSmsTwoWay SmsType = 4
)

func (e SmsType) ToPointer() *SmsType {
	return &e
}
