// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SmsType - SMS type according to the table
//
// |type|Description|
// |----|-----------|
// |  1 |  SMS PRO  |
// |  3 |  SMS ECO  |
// |  4 |  SMS 2WAY |
type SmsType int64

const (
	SmsTypeSmsPro    SmsType = 1
	SmsTypeSmsEco    SmsType = 3
	SmsTypeSmsTwoWay SmsType = 4
)

func (e SmsType) ToPointer() *SmsType {
	return &e
}
