workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Client -OAS:
        inputs:
            - location: ..\..\..\app\libs\restApi\openapi.yaml
        overlays:
            - location: .speakeasy\speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/intermedia/gsmservice-pl/client--oas
targets:
    client:
        target: go
        source: Client -OAS
